name: Backend Node.js con GitHub Actions

on:
  push:
    branches:
      - gh-pages  # Ejecutar el workflow en la rama gh-pages o la rama que desees

jobs:
  build-and-run-backend:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Clonar el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3. Instalar dependencias
      - name: Install dependencies
        run: npm install

      # 4. Instalar ngrok
      - name: Install ngrok
        run: |
          curl -s https://ngrok.com/download | tar xz -C /tmp
          mv /tmp/ngrok /usr/local/bin/ngrok

      # 5. Configurar ngrok con el authtoken
      - name: Set up ngrok auth token
        run: ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      # 6. Ejecutar el servidor Node.js y ngrok en segundo plano
      - name: Run backend server with ngrok
        run: |
          nohup ngrok http 3000 &   # Iniciar ngrok en segundo plano
          nohup node server.js &   # Iniciar el servidor Node.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
