name: Build and Notify Central Repo

on:
  push:
    paths:
      - "UserCode.java" # Sólo se dispara si este archivo cambia
    branches:
      - gh-pages

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Listar los archivos para verificar
      - name: Verify static build
        run: |
          echo "Listing files in the repository:"
          ls -la

      # 3. Comprimir el archivo `UserCode.java`
      - name: Zip UserCode.java
        run: zip UserCode.zip UserCode.java

      # 4. Subir el archivo como artefacto
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: user-code-artifact
          path: UserCode.zip

  notify-central-repo:
    runs-on: ubuntu-latest
    needs: build-and-upload

    steps:
      # 1. Obtener el ID del artefacto generado
      - name: Get Artifact ID
        id: get-artifact
        run: |
          ARTIFACT_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/artifacts \
            | jq -r '.artifacts[0].id')
          echo "artifact-id=$ARTIFACT_ID" >> $GITHUB_ENV

      # 2. Notificar al repositorio central
      - name: Notify central repo
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.SPRING_BOOT_EDITOR_ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/null-point-sys/spring_boot_rest_api_crud/dispatches \
          -d '{"event_type":"new-artifact", "client_payload": {"artifact_id": "${{ env.artifact-id }}", "repo_owner": "null-point-sys", "repo_name": "spring_boot_editor"}}'

      # 3. Disparar el evento repository_dispatch hacia el repositorio receptor
      - name: Trigger repository_dispatch in front_testing
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.SPRING_BOOT_EDITOR_ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/null-point-sys/spring_boot_rest_api_crud/dispatches \
          -d '{"event_type": "new-artifact", "client_payload": {"artifact_id": "${{ env.artifact-id }}", "repo_owner": "null-point-sys", "repo_name": "spring_boot_editor"}}'
